name: CI - Build and Push

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Make application.properties
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Rename jar
        run: mv target/*.jar target/app.jar

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

      - name: Checkout app-infra repo
        uses: actions/checkout@v4
        with:
          repository: cjsqudwns/app-infra
          path: app-infra
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Update image tag in app-infra
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}|" app-infra/base/api/deployment.yaml

      - name: Commit and Push
        run: |
          cd app-infra
          git config --local user.email "cjsqudwns@gmail.com"
          git config --local user.name "cjsqudwns"
          git add .
          git commit -m "Update image tag to latest"
          git push
